[[redirects]]
  from = "/referencement-seo/levallois-perret"
  to = "/agence-web-levallois-perret"
  status = 301
  force = true

[[redirects]]
  from = "/creation-site-web/levallois-perret"
  to = "/agence-web-levallois-perret"
  status = 301
  force = true

[[redirects]]
  from = "/:splat/"
  to = "/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/sitemap.xml"
  to = "https://iskxljribvfypkyappku.supabase.co/functions/v1/generate-sitemap"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
